---
title: "Resources"
format: 
  html: 
    toc: false
---

There are many resources available if you would like to keep building your skills in R, data science, and data visualization beyond this course. Here, we have compiled a list of some places you might turn to for additional nuggets of knowledge.

## Learn More!

- [learn-r by Jeff Oliver](https://jcoliver.github.io/learn-r/)  
  A helpful introductory lesson sequence in R developed by Jeff Oliver, one of the contributors to this course.

- [Hello Data Science](https://hellodata.science/)  
  A beginner-friendly resource designed to introduce students to data science concepts and tools in a clear, accessible way.

- [R for Data Science](https://r4ds.hadley.nz/)  
  A widely used open-access textbook for learning R, data wrangling, visualization, and analysis.

- [The Carpentries](https://carpentries.org/)  
  A well-known community focused on teaching foundational coding and data skills for research. Their workshops and teaching materials are especially helpful for beginners.

- [From Data to Viz](https://www.data-to-viz.com/)  
  A guide for choosing the right kind of visualization for your data.

- [R Charts](https://r-charts.com/)  
  A useful reference for creating and customizing charts and graphs in R.