---
title: "Course Structure"
format:
  html:
    toc: false
---

## The Full Course Cheese Board

This page serves as an inventory of the material associated with each subsection of this site. These are also available in the Data in the Wild Github repository, which can be accessed [here](https://github.com/BiodiversityDataScienceCorp/DataInTheWild_UA.git).

***Note*****:** The instructor versions of lessons are also available as PDFs, and they can be downloaded from the righthand table of contents within the respective module subsection (e.g. Click on 1.1: Introduction to RStudio in the left sidebar \> navigate your attention to the table of contents on the right side of the screen \> the link to download the PDF is at the bottom).

+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Module        | Title                                                       | Lecture / Code-along (.Rmd)                                                                                                                                            | Data sets (.csv)                                                                                                            | Assignments (.Rmd)                                                                                                                                                  |
+:=============:+:===========================================================:+:======================================================================================================================================================================:+:===========================================================================================================================:+:===================================================================================================================================================================:+
| 1.1           | Introduction to RStudio                                     | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/lessons/Module1_1_IntrotoRStudio.Rmd)                   | [.zip](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/zipped_data/M1_data.zip)         | [Assignment 2](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/module_1/assignments/Module1_Assignment2.Rmd) |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/lessons/Module1_1_IntrotoRStudio_Instructor.Rmd)     |                                                                                                                             | [Assignment 3](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/module_1/assignments/Module1_Assignment3.Rmd) |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1.2           | Introduction to Coding                                      | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/lessons/Module1_2_IntrotoCoding.Rmd)                    |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/lessons/Module1_2_IntrotoCoding_Instructor.Rmd)      |                                                                                                                             |                                                                                                                                                                     |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1.3           | 2-dimensional Data and the `tidyverse`                      | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/lessons/Module1_3_tidyverse.Rmd)                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/lessons/Module1_3_tidyverse_Instructor.Rmd)          |                                                                                                                             |                                                                                                                                                                     |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.1           | Introduction to Descriptive Statistics & Data Visualization | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_2/lessons/Module2_1_DescriptiveStats.Rmd)                 | [.zip](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/zipped_data/M2_data.zip)         | [Assignment 1](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/module_2/assignments/Module2_Assignment1.Rmd) |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_2/lessons/Module2_1_DescriptiveStats_Instructor.Rmd)   |                                                                                                                             | [Assignment 2](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/module_2/assignments/Module2_Assignment2.Rmd) |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             | [Assignment 3](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/module_2/assignments/Module2_Assignment3.Rmd) |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.2           | Writing Functions                                           | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_2/lessons/Module2_2_Functions.Rmd)                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_2/lessons/Module2_2_Functions_Instructor.Rmd)          |                                                                                                                             |                                                                                                                                                                     |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.3           | Introduction to Data Visualization                          | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_2/lessons/Module2_3_DataViz.Rmd)                          |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_2/lessons/Module2_3_DataViz_Instructor.Rmd)            |                                                                                                                             |                                                                                                                                                                     |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.4           | Plotting in `ggplot2`                                       | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_2/lessons/Module2_4_geoms.Rmd)                            |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_2/lessons/Module2_4_geoms_Instructor.Rmd)              |                                                                                                                             |                                                                                                                                                                     |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.5           | Module 2 Wrap-Up                                            | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_2/lessons/Module2_5_WrapUp.Rmd)                           |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_2/lessons/Module2_5_WrapUp_Instructor.pdf)             |                                                                                                                             |                                                                                                                                                                     |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3.1           | Leopard Seals: Introducing a New Problem                    | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_3/lessons/Module3_1_LeopardSeals.Rmd)                     | [.zip](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/zipped_data/M3_data.zip)         | [Assignment 1](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/module_3/assignments/Module3_Assignment1.Rmd) |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_3/lessons/Module3_1_LeopardSeals_Instructor.Rmd)       |                                                                                                                             | [Assignment 2](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/module_3/assignments/Module3_Assignment2.Rmd) |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             | [Assignment 3](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/module_3/assignments/Module3_Assignment3.Rmd) |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3.2           | T-Tests                                                     | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_3/lessons/Module3_2_T-Tests.Rmd)                          |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_3/lessons/Module3_2_T-Tests_Instructor.Rmd)            |                                                                                                                             |                                                                                                                                                                     |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3.3           | ANOVA                                                       | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_3/lessons/Module3_3_ANOVA.Rmd)                            |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_3/lessons/Module3_3_ANOVA_Instructor.Rmd)              |                                                                                                                             |                                                                                                                                                                     |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3.4           | Combining Datasets                                          | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_3/lessons/Module3_4_Combining_Datasets.Rmd)               |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_3/lessons/Module3_4_Combining_Datasets_Instructor.Rmd) |                                                                                                                             |                                                                                                                                                                     |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3.5           | K-Nearest Neighbors                                         | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_3/lessons/Module3_5_KNN.Rmd)                              |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_3/lessons/Module3_5_KNN_Instructor.Rmd)                |                                                                                                                             |                                                                                                                                                                     |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4.1           | Roads and Regression                                        | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_4/lessons/Module4_1_RoadsandRegression.Rmd)               | [.zip](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/zipped_data/M4_data.zip)         | [Assignment 1](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/module_4/assignments/Module4_Assignment1.Rmd) |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_4/lessons/Module4_1_RoadsandRegression_Instructor.Rmd) |                                                                                                                             | [Assignment 2](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/module_4/assignments/Module4_Assignment2.Rmd) |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             | [Assignment 3](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/module_4/assignments/Module4_Assignment3.Rmd) |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             | [Final Project](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/refs/heads/main/modules/final_project/FinalAssignment_Sp2024.Rmd)    |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4.2           | Multiple Regression                                         | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_4/lessons/Module4_2_MultipleRegression.Rmd)               |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             |                                                                                                                                                                        |                                                                                                                             |                                                                                                                                                                     |
|               |                                                             | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_4/lessons/Module4_2_MultipleRegression_Instructor.Rmd) |                                                                                                                             |                                                                                                                                                                     |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Final Project |                                                             |                                                                                                                                                                        | [.zip](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/zipped_data/final_proj_data.zip) | [Assignment Guidelines](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/final_project/FinalAssignment.pdf)              |
+---------------+-------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+