{
  "hash": "23ec4a093836ed8693535a803c1a240b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3.2: T-Tests\"\nauthor: \"Ellen Bledsoe, Lily McMullen\"\nformat:\n  html:\n    toc: true\n---\n\n\n\n# Comparing Two Means\n\n## Learning Outcomes\n\n-   Students will be able to identify appropriate independent and dependent variables for a t-test.\n-   Students will be able to write null and alternative hypotheses.\n-   Students will be able to run a t-test in R using `t.test()`.\n-   Students will be able to interpret t-test output including the t-statistic, p-value, and confidence interval.\n\nWhen we are comparing data from two groups, we often want to compare the mean values of the different groups to see if there are differences. We can do this in a number of ways:\n\n-   Numerically (descriptive statistics)\n-   Visually\n-   Statistically (inferential statistics)\n\nIn this course so far, we have done the first 2: by calculating the mean values of groups and by plotting histograms, density plots, and box-plots.\n\nIn this lesson, we will be exploring the statistical side using inferential statistics. Once again, we will be using our collars data, focusing on the battery life and the signal distance.\n\nLet's get set-up by loading the tidyverse and reading in our data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n::: instructor-only\n**Answer:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\ncollars <- read_csv(\"data/collar_data.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 100 Columns: 5\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): maker\ndbl (4): collar_id, battery_life, signal_distance, fail\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n:::\n\nLet's take a quick look at the data structure to remind ourselves what data we are using.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# View first few rows\nhead(collars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  collar_id maker          battery_life signal_distance  fail\n      <dbl> <chr>                 <dbl>           <dbl> <dbl>\n1         1 Collarium Inc.        110.            4188.     0\n2         2 Collarium Inc.         98.1           4166.     0\n3         3 Collarium Inc.        103.            4183.     0\n4         4 Collarium Inc.         97.8           4212.     0\n5         5 Collarium Inc.        120.            4158.     0\n6         6 Collarium Inc.        121.            4191.     0\n```\n\n\n:::\n:::\n\n\nBefore we dive in, if you need a refresher on inferential statistics, check out [this powerpoint](https://docs.google.com/presentation/d/1N2fxiNa5mw_fVukXFPWMuynFcts3gD4SvMO4VKzyZFI/edit?usp=sharing).\n\n## T-Tests\n\nWhen we have a categorical variable with 2 categories, the statistical tests we use to determine if the two categories are *statistically significantly different* from each other are called **t-tests**.\n\n### When to Use a t-test\n\nTo run a t-test, the following things need to be true:\n\n-   The variable that we use to create our groups (***independent*** variable) is *categorical* and has only 2 categories.\n-   The variable that we want to compare between groups (***dependent*** or response variable) is *numeric*.\n\n#### Independent vs. Dependent Variables\n\nWhy are the variables called *independent* and *dependent*, do you think?\n\n-   The **independent** variable is the *cause*. It does not change in response to other variables in the data.\n-   The **dependent** variable is the *effect*. We expect that it does change in response to the independent variable.\n\nWant more info on independent vs. dependent variables? Check out [this link](https://www.scribbr.com/methodology/independent-and-dependent-variables/).\n\n### Hypothesis Testing\n\nThe first step in running any statistical test (t-test or otherwise) is *hypothesis testing*.\n\nWe build our hypotheses around our independent and dependent variables.\n\nIn this case, we want to know if there is a *meaningful* (read: statistical) difference between each collar manufacturer in their average values for battery life. To start, let's identify our independent and dependent variables:\n\n-   **Independent:** Maker, categorical\n-   **Dependent:** Battery_life, continuous/numerical\n\nBased on our question, we can now set up two different statistical hypotheses: the null hypothesis and the alternative hypothesis.\n\nThe null hypothesis always states that there is no difference or no relationship. We can think of the null hypothesis as our starting place or our default assumption. The alternative hypothesis is, well, the alternative to the null hypothesis. For example:\n\n-   **Null Hypothesis** ($H_{0}$): There is *no* difference in the means of battery life between the two collar makers\n-   **Alternative Hypothesis** ($H_{A}$): There *is* a difference in the mean battery life between the two collar makers\n\nHow can we determine whether we should *not reject* (\"accept\") or *reject* the null hypothesis? That's where statistics come in.\n\n*(Note: For statistical reasons beyond the scope of this course, we never say we \"accept\" the alternative hypothesis, we only say we \"reject\" or \"fail to reject\" the null hypothesis.)*\n\n### Running a t-test\n\nThere is a set of statistical tools that can help us determine whether or not there is a difference between 2 means. These tools are called t-tests.\n\nLet's briefly remind ourselves of the logic here.\n\n1.  Our data are a *sample* of a larger *population* (think of the population as all of the collars ever produced by both companies).\n2.  We're interested in the difference in the means between the two groups.\n    -   If they're exactly the same, the difference in means would be 0.\n    -   If they're different, the difference between the means will be something either larger or smaller than 0.\n3.  However, because we only have data from a random *sample* of collars, there will be some variation in our numbers due to sampling error.\n4.  We want to know if the difference in means is due to sampling error alone or due to an actual difference between manufacturers.\n\nThe t-test helps us determine whether the observed difference in means is larger than what we would expect from random sampling variation alone.\n\nLet's run some code to perform our first t-test!\n\nWe use a function called `t.test()`.\n\n-   The first argument describes the test we want to run using column names. The structure is always `dependent ~ independent`.\n-   The second argument is the data frame we are referencing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A t-test for battery life\nt.test(battery_life ~ maker, data = collars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  battery_life by maker\nt = -5.4807, df = 92.449, p-value = 3.646e-07\nalternative hypothesis: true difference in means between group Budget Collars LLC and group Collarium Inc. is not equal to 0\n95 percent confidence interval:\n -14.446256  -6.761484\nsample estimates:\nmean in group Budget Collars LLC     mean in group Collarium Inc. \n                        100.5891                         111.1929 \n```\n\n\n:::\n:::\n\n\nThankfully, the code isn't too onerous. Interpreting the results is a different matter, though...\n\n### Interpreting the Results of a t-test\n\nLet's talk through it:\n\n-   `t`: this is what we call the t-value, or t-statistic.\n    -   Here, it is a metric of how different the difference of the two means is from 0.\n    -   Note that it doesn't correspond *directly* to the difference, it is taking into account the actual difference as well as the variation in the data sets.\n    -   Take home: big values (can be positive or negative) indicate a big difference from 0 while small values mean the difference is close to 0.\n-   `df`: stands for *degrees of freedom*\n    -   It's a measure of your sample size and some other stuff, honestly, this is not something we're really going to focus on here.\n-   `p-value`: a measure of certainty of the difference outlined in the `t-statistic` above\n    -   For the test above, our p-value is *very* small: 0.0000003646.\n        -   Wait, how did I get from `3.646e-7` to 0.0000003646?\n            -   The `e-7` means that we need to move the decimal space to the left 7 times, creating a very small number!\n            -   If the number after the `e` were positive (e.g., `e+5`), I would move the decimal 5 places to the right, creating a very big number.\n    -   This means that there is an extremely low probability that the difference in means is due to random variation in our sample alone.\n    -   There are a lot of benchmarks in different fields for what this value should be below to consider the difference *significant*; typically a p-value below 0.05 is considered significant.\n-   `95 percent confidence interval`: this is the range that we can expect the difference in the two means to fall in 95% of the time given the data.\n    -   The difference in means of Budget Collars and Collarium: 100.59 - 111.19 = -10.6\n    -   If we randomly sample a group of collars from the \"population\", the difference in means will fall between -14.4 and -6.8 about 95% of the time\n    -   the values are negative because the smaller group (Budget Collars) is first, so we are subtracting the larger number (Collarium average) from the smaller number (Budget Collars average)\n\nLet's quickly remind ourselves how p-values work:\n\n![](assets/Explaining-P-values_Composite-with-labels.png)\n\nGiven our very small p-value here, what can we conclude?\n\n-   Is the p-value below our cut-off for significance (0.05)?\n-   Is our result statistically significant?\n-   Does that mean we should or should not reject the null hypothesis?\n-   So...is there a \"real\" difference in the means between the two companies or not?\n\n#### Let's Practice!\n\nWe want to know if there is a significant difference in the average signal distances for the two companies.\n\n1.  Identify your independent and dependent variables.\n\n2.  Write out your null and alternative hypotheses.\n\n3.  Run the t-test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n4.  Interpret the t-test:\n\n-   Is the p-value below our cut-off for significance (0.05)?\n-   Is our result statistically significant?\n-   Does that mean we should or should not reject the null hypothesis?\n-   So... is there a \"real\" difference in the means between the two companies or not?\n\n::: instructor-only\n**Answers:**\n\n1.  **Independent:** maker (categorical) \\| **Dependent:** signal_distance (numeric)\n\n2.  **Null Hypothesis** ($H_{0}$): There is *no* difference in average signal distance between collar makers\\\n    **Alternative Hypothesis** ($H_{A}$): There *is* a difference in average signal distance between collar makers\n\n3.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(signal_distance ~ maker, data = collars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  signal_distance by maker\nt = 7.322, df = 97.416, p-value = 7.055e-11\nalternative hypothesis: true difference in means between group Budget Collars LLC and group Collarium Inc. is not equal to 0\n95 percent confidence interval:\n 37.26594 64.97933\nsample estimates:\nmean in group Budget Collars LLC     mean in group Collarium Inc. \n                        4255.095                         4203.972 \n```\n\n\n:::\n:::\n\n\n4.  \n\n-   p-value below 0.05? **Yes**\n-   Statistically significant? **Yes**\n-   Reject or fail to reject null? **Reject**\n-   Real difference between companies? **Yes**\n\n**Instructor Note:** Students should note that signal distance IS significantly different between makers. Budget Collars LLC transmits farther on average (\\~4255) vs Collarium Inc. (\\~4204). Combined with the battery life result, this confirms the engineering trade-off seen visually in 3.1: Budget Collars LLC trades battery life for signal range.\n:::",
    "supporting": [
      "module3_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}