{
  "hash": "1b17a5009ee073df0c4cab6ea2856da7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"4.4: Multiple Regression\"\nauthor: \"Ellen Bledsoe\"\nformat:\n  html:\n    toc: true\n---\n\n\n\n# Multiple Regression\n\n## Learning Outcomes\n\n-   Students will be able to explain when and why a multiple regression is used.\n-   Students will be able to run a multiple regression in R and interpret the output for each variable.\n-   Students will be able to explain what an interaction term means and identify it visually from a plot.\n-   Students will be able to run a model with an interaction term and interpret the results.\n\nSometimes (often!), we have multiple independent variables that we think might be influencing our dependent variable. In order to take into account more than one variable, we can perform what is called a \"multiple regression.\"\n\nMultiple regressions can become complicated beasts, but we are going to focus on adding in just one additional variable and how it can impact our interpretations.\n\nLet's use some penguins nesting site data to demonstrate.\n\n## Set-Up\n\nLoad the tidyverse and read in \"data/site_changes.csv\", saving it as `site_data`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n::: instructor-only\n**Answer:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nsite_data <- read_csv(\"data/site_changes.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 200 Columns: 6\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (6): site_id, year, tussocks, dist_to_water, stone_size, num_nests\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# This converts the year column to a categorical variable rather than a number\n# We need to run this for the regression models below to work!\nsite_data <- site_data %>% \n  mutate(year = as.factor(year))\n```\n:::\n\n\nWe want to understand what factors influence penguin nesting. We wouldn't want to build our road through important penguin nesting territories!\n\nLet's quickly take a look at the data we have.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(site_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  site_id year  tussocks dist_to_water stone_size num_nests\n    <dbl> <fct>    <dbl>         <dbl>      <dbl>     <dbl>\n1       1 1971      4.95          26.6       45.0        25\n2       2 1971      3.60          28.2       45.1        18\n3       3 1971      3.71          24.1       46.3        27\n4       4 1971      5.14          29.6       43.3        16\n5       5 1971      6.71          27.9       46.6        15\n6       6 1971      5.16          26.7       47.1        29\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(site_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  site_id year  tussocks dist_to_water stone_size num_nests\n    <dbl> <fct>    <dbl>         <dbl>      <dbl>     <dbl>\n1      95 2011      7.46          25.8       42.1        19\n2      96 2011      6.29          21.9       43.7        31\n3      97 2011      7.10          21.7       45.5        25\n4      98 2011      6.61          21.9       42.3        18\n5      99 2011      6.74          21.7       41.7        29\n6     100 2011      7.50          18.6       40.1        31\n```\n\n\n:::\n:::\n\n\nOkay, it looks like we have data for 100 different sites collected in two different years. We have the number of penguin nests, which is the variable that we are interested in. We also have a few other variables that might be influencing the number of nests at each site: the number of tussocks of grass, the stone size, the distance to water, and the year that data were collected.\n\nLet's start with looking at how the number of grass tussocks affects nest numbers.\n\n### Regression Model (1 Independent Variable)\n\nLet's start by plotting our tussocks data and run a model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(site_data, aes(x = tussocks, y = num_nests)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  labs(x = \"Tussocks\", y = \"Number of Nests\") +\n  theme_classic()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](module4_4_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThis model is showing us a positive relationship between the number of tussocks and number of nests. Let's run our linear regression model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntussocks_model <- lm(num_nests ~ tussocks, data = site_data)\nsummary(tussocks_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = num_nests ~ tussocks, data = site_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-16.0717  -4.5553   0.2871   4.4302  14.1867 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  13.0711     2.0555   6.359 1.37e-09 ***\ntussocks      1.3299     0.3322   4.004 8.81e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.384 on 198 degrees of freedom\nMultiple R-squared:  0.0749,\tAdjusted R-squared:  0.07023 \nF-statistic: 16.03 on 1 and 198 DF,  p-value: 8.81e-05\n```\n\n\n:::\n:::\n\n\nOur model is telling us that the relationship between the number of nests and number of tussocks is highly significant.\n\n::: instructor-only\n**Instructor Note:** p = 8.81e-05, highly significant. The positive coefficient (1.33) means more grass tussocks predict more nests. R\\^2 = 0.075, so tussocks explains about 7.5% of variation on its own.\n:::\n\n### Running a Multiple Regression\n\nWhat if we incorporate the year the data were collected into our model? Adding an additional independent variable to our model can change how we interpret the results.\n\nFirst, let's plot a multiple scatterplot. Do we see the same patterns?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(site_data, aes(x = tussocks, y = num_nests, color = year)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  labs(x = \"Tussocks\", y = \"Number of Nests\") +\n  theme_classic()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](module4_4_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nHuh, that looks a little bit different...we no longer seem to have much of a positive relationship. Instead, both lines are looking pretty flat! Let's see what happens when we add year into our regression model.\n\nBy adding the year variable into the model, we are also asking if the number of nests changes by year. Does it change our significance?\n\nThe way we add an independent variable is with a `+` in the equation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntussocks_model <- lm(num_nests ~ tussocks + year, data = site_data)\nsummary(tussocks_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = num_nests ~ tussocks + year, data = site_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-15.644  -4.580   0.424   4.504  12.259 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  19.4867     2.5055   7.777 4.05e-13 ***\ntussocks     -0.1868     0.4844  -0.386      0.7    \nyear2011      5.4818     1.3167   4.163 4.69e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.136 on 197 degrees of freedom\nMultiple R-squared:  0.1497,\tAdjusted R-squared:  0.1411 \nF-statistic: 17.34 on 2 and 197 DF,  p-value: 1.154e-07\n```\n\n\n:::\n:::\n\n\nWe have a bunch of estimates now! Don't worry about putting these into an equation :) We are only focusing on significance values.\n\n-   `tussocks`: the p-value for the tussocks row (p = 0.7) shows whether the number of tussocks is a significant driver of nest numbers (it isn't!)\n-   `year2011`: this p-value is significant (p = 4.69e-05)---year does seem to impact how many nests there are\n    -   (you don't need to know this, but if you are curious...): the reason this says `year2011` and not just `year` is because year is acting as a category, and we can get different coefficient estimates for year. The first option in the categorical variable (1971, in this case) is incorporated into the current intercept estimate, so `year2011` indicates the difference from the original.\n\n::: instructor-only\n**Instructor Note:** Once the model accounts for the fact that nest numbers changed between years, tussocks no longer explains any additional variation. The tussocks effect in the simple model was being driven by the year difference, not by tussocks themselves.\n:::\n\n### Interactions\n\nSometimes, we might expect that there will be an interactive effect between the two independent variables we are including in our model. This means that the combinations of independent variables impact the dependent variable in different ways.\n\nWe can typically spot interactive effects in a plot when the slopes of the regression lines differ from each other a lot.\n\nLet's talk through the visual demonstration below to hopefully get a better understanding of how interaction effects work. These plots are showing different possible relationships between two independent variables: how many cups of coffee someone has had and whether they drank them in the morning or the afternoon (categorical variable), and how those might impact the dependent variable, how long it takes to complete a task.\n\n-   The top two panels show examples of no interactive effect. It looks like there is an effect of time of day; in each, drinking coffee in the morning makes tasks take longer. However, the *slopes* between time of day are the same. In the first panel (top left), there also looks to be an impact from the number of cups of coffee.\n-   The bottom four panels demonstrate possible variations of *interactive* effects. Not only does time of day and/or number of cups of coffee impact how long it takes to complete a task, but those independent variables affect how long it takes to complete a task *in different ways*.\n\n![](assets/coffee_interaction.jpg){width=\"50%\"}\n\nIn our example above, an interactive effect between tussocks and year would mean that we think the number of tussocks impacts the number of nests *in different ways* between the two categories (year). Since the slopes between the years don't look very different, we aren't really expecting there to be a significant interaction, but let's check anyway.\n\nLet's run a model that includes the interaction term in our model. To do this, we will use an asterisk (`*`) instead of a plus sign.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntussocks_model <- lm(data = site_data, num_nests ~ tussocks * year)\nsummary(tussocks_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = num_nests ~ tussocks * year, data = site_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.5186  -4.5456   0.4779   4.4342  12.1779 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       18.23648    3.88911   4.689 5.13e-06 ***\ntussocks           0.06251    0.76571   0.082    0.935    \nyear2011           7.91428    5.92732   1.335    0.183    \ntussocks:year2011 -0.41675    0.99005  -0.421    0.674    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.149 on 196 degrees of freedom\nMultiple R-squared:  0.1505,\tAdjusted R-squared:  0.1375 \nF-statistic: 11.57 on 3 and 196 DF,  p-value: 5.12e-07\n```\n\n\n:::\n:::\n\n\nWe can see that we still have estimates for both tussocks and year alone. However, we now also have something new: our interaction term, `tussocks:year2011`.\n\nIt turns out that adding in the year variable has changed the significance in our model, and the interaction term is also not significant.\n\n-   The positive relationship we originally observed is no longer present when we account for the year.\n-   There is no significant interaction, meaning that penguins respond to the number of tussocks the same way in each year.\n-   Interestingly (and maybe frustratingly), the significant effect of year that we saw before is also gone.\n    -   This is a confusing bit of statistics, and the full explanation is beyond the scope of this course. Similar things sometimes happen when we have a significant overall ANOVA but no significant pairwise comparisons.\n    -   What is happening behind the scenes has to do with how the information for each variable is being partitioned. Adding new variables (including an interaction) decreases the likelihood of any individual variable being significant.\n    -   For this course, the goal is to correctly interpret the significance values, not to explain why this happens.\n\nLet's explore another example to get a better understanding.\n\n### Practicing with Stone Size\n\nLet's investigate how stone size influences nest numbers. Gentoo penguins build their nests out of stones (they actually court their penguin partner with stones, too)!\n\n![](assets/gentoo-penguin-cornell-lab2.jpg){width=\"50%\"}\n\nStart by plotting the relationship between stone size and the number of nests.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(site_data, aes(x = stone_size, y = num_nests)) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](module4_4_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nWhat does the regression model tell us?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstone_size_mod = lm(num_nests ~ stone_size, data = site_data)\nsummary(stone_size_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = num_nests ~ stone_size, data = site_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.0069  -4.9641  -0.3939   4.0581  15.5562 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -5.1572     5.9598  -0.865    0.388    \nstone_size    0.5940     0.1344   4.418 1.64e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.333 on 198 degrees of freedom\nMultiple R-squared:  0.08974,\tAdjusted R-squared:  0.08515 \nF-statistic: 19.52 on 1 and 198 DF,  p-value: 1.637e-05\n```\n\n\n:::\n:::\n\n\nHow do we interpret this model?\n\n::: instructor-only\n**Instructor Note:** Stone size is a significant positive predictor of nest numbers (p = 1.64e-05). Larger stones are associated with more nests. R\\^2 = 0.090, so stone size explains about 9% of variation. Significant, but a weak predictor on its own.\n:::\n\nNext, let's add year in the mix. First, plot the relationship between the number of nests and stone size by year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(site_data, aes(x = stone_size, y = num_nests, color = year)) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](module4_4_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nThis plot looks pretty different from the one with tussocks. First, let's see what happens when we add the year variable *without* the interactive term. To do that, we use a plus sign (`+`), not an asterisk (`*`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstone_size_mod = lm(num_nests ~ stone_size + year, data = site_data)\nsummary(stone_size_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = num_nests ~ stone_size + year, data = site_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.3183  -4.3173  -0.4471   4.7328  13.0118 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -9.5585     5.4622  -1.750   0.0817 .  \nstone_size    0.6335     0.1224   5.175  5.6e-07 ***\nyear2011      5.3092     0.8155   6.510  6.1e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.76 on 197 degrees of freedom\nMultiple R-squared:  0.2509,\tAdjusted R-squared:  0.2433 \nF-statistic: 32.99 on 2 and 197 DF,  p-value: 4.387e-13\n```\n\n\n:::\n:::\n\n\nHow do we interpret this multiple regression model?\n\n::: instructor-only\n**Instructor Note:** Both stone size (p = 5.6e-07) and year (p = 6.1e-10) are highly significant. Unlike tussocks, stone size remains a significant predictor even after accounting for year. The model improved substantially. R\\^2 went from 0.090 to 0.251, meaning the two-variable model explains 25% of variation vs. 9% for stone size alone.\n:::\n\nFrom the ggplot above, we can see that the slopes for the two different years are quite different: one is pretty flat while the other is definitely positive. Different slopes often indicate that an *interaction* might be at work. Let's find out. Run another multiple regression model, this time adding in the interactive effect (`*`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstone_size_mod = lm(num_nests ~ stone_size * year, data = site_data)\nsummary(stone_size_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = num_nests ~ stone_size * year, data = site_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.3384  -4.1293   0.1189   3.7493  11.7629 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         -37.5446     7.7555  -4.841 2.61e-06 ***\nstone_size            1.2643     0.1744   7.251 9.35e-12 ***\nyear2011             55.3424    10.3558   5.344 2.51e-07 ***\nstone_size:year2011  -1.1314     0.2335  -4.845 2.57e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.457 on 196 degrees of freedom\nMultiple R-squared:  0.331,\tAdjusted R-squared:  0.3208 \nF-statistic: 32.33 on 3 and 196 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nWow, a bunch of significant variables! What does that mean, exactly?\n\n::: instructor-only\n**Instructor Note:** All three terms are significant: stone_size (p = 9.35e-12), year2011 (p = 2.51e-07), and the interaction stone_size:year2011 (p = 2.57e-06).\n\nThe negative interaction coefficient (-1.13) means the effect of stone size on nest numbers is weaker in 2011 than in 1971.\n:::\n\nNot only are stone size and year significant, but so is the interaction between stone size and year. What does this mean? It means that penguins in different years seems to respond differently to stone size. In 1971, the number of nests increases with stone size, but in 2011, the number of nests doesn't seem impacted by stone size. Therefore, there is an *interaction* between stone size and year.\n\n### Resources\n\nStill feeling a bit confused about multiple regression and interactions? [This website](https://stattrek.com/multiple-regression/interaction?tutorial=reg) does a nice job of laying out what interactions are.\n\nAlso, if you are interested in how we select which model is the best model, [this article](https://www.statology.org/aic-in-r/) is a decent place to start.",
    "supporting": [
      "module4_4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}