{
  "hash": "f7458f8ecd66baf5d5856270ffa4d156",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: '5.3: Comparing Populations'\nauthor: \"Jessie Golding, Desiree Andersen, Ellen Bledsoe\"\nformat:\n  html:\n    toc: true\n---\n\n\n\n# Comparing Populations\n\n## Learning Outcomes\n\n-   Students will be able to add logistic growth model curves to a `ggplot2` visualization using `predict()` and `geom_line()`.\n-   Students will be able to estimate and compare carrying capacities across multiple populations.\n-   Students will be able to select and run an appropriate statistical test to compare mean population sizes across groups.\n-   Students will be able to make a data-driven recommendation about which population to fish.\n\nThroughout this module, we have learned how populations demonstrating exponential growth and logistic growth differ from one another, both conceptually and visually.\n\nWhile we have fit models to some of these populations (specifically, logistic growth models), we have done so in order to estimate the carrying capacity of the population rather than to use inferential statistics to determine if the populations are statistically significantly different from one another.\n\nIn this lesson, we are going to learn how to (a) add those logistic growth models to our data visualizations and (b) compare populations statistically.\n\n## Set Up\n\nAs always, we need to start by loading the packages we are going to use along with our data.\n\nFirst, let's load our packages. We are going to be using both the `tidyverse` and `drc` packages in this lesson, so we need to load both of them.\n\nThen, load in our data \"comparing_populations.csv\" as `pops`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n::: instructor-only\n**Answer:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(drc)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: MASS\n\nAttaching package: 'MASS'\n\nThe following object is masked from 'package:dplyr':\n\n    select\n\n\n'drc' has been loaded.\n\nPlease cite R and 'drc' if used for a publication,\nfor references type 'citation()' and 'citation('drc')'.\n\n\nAttaching package: 'drc'\n\nThe following objects are masked from 'package:stats':\n\n    gaussian, getInitial\n```\n\n\n:::\n\n```{.r .cell-code}\npops <- read_csv(\"data/comparing_populations.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 78 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): population\ndbl (2): year, abund\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n:::\n\nWe can use the `head()` function to take a look at the data. What data do we have?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(pops)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n   year abund population\n  <dbl> <dbl> <chr>     \n1     0    51 NE        \n2     1    70 NE        \n3     2   164 NE        \n4     3   248 NE        \n5     4   431 NE        \n6     5   567 NE        \n```\n\n\n:::\n:::\n\n\nAfter inspecting our dataset, it looks as though we have more time-series data of population abundances. It isn't immediately clear how many populations there are, but perhaps the populations are named after their locations (\"NE\" could stand for \"Northeast\").\n\n## Visually\n\nLet's first start our investigation of these populations by plotting the data points as a scatterplot.\n\nAs we have done throughout this module, we will want the variable representing time to be on the x-axis and the population abundance (N) on the y-axis.\n\nWe will also want the data points to be distinguished by which population they are from, so we need to specify the `color` argument within the `aes()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pops, aes(year, abund, color = population)) +\n  geom_point() + \n  labs(x = \"Year\",\n       y = \"Abundance\",\n       color = \"Fish Population\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](module5_3_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### Interpretation\n\nBased on the plot, what do you notice about these populations?\n\n-   Are they more likely exhibiting exponential or logistic growth? Why?\n-   How do the populations appear to differ from one another?\n\nGiven your answers to the questions above, what might be a good next step?\n\n::: instructor-only\n**Instructor Note:** All three populations show logistic growth. The NE population appears to reach the highest abundance, SW the lowest, with SE in between.\n\nStudents should suggest fitting logistic models to each population to estimate carrying capacities, then running a statistical test to compare them.\n:::\n\n## Numerically\n\nWhen comparing different categories or groups (in this case, comparing different populations), we typically compare them both visually and numerically before conducting statistical tests.\n\nSince we have already made visual comparisons, let's compare the populations numerically.\n\nTypically, we have compared groups with measures of central tendency and measures of variability. Do you think that is what we should do here? Why or why not?\n\n::: instructor-only\n**Instructor Note:** Not quite, calculating a mean across all time points would mix the growth phase with the stable phase and give a misleading number.\n\nA better approach is to compare the carrying capacities from the logistic models. Once we restrict to the leveled-off period (year 15+), then comparing means with an ANOVA makes sense.\n:::\n\n### Separate Populations\n\nUnlike our typical procedure, in order to fit logistic models to each population, our simplest way forward will be to create one data frame for each population.\n\n| NOTE: in case you are wondering, yes, there are definitely ways to fit a logistic model to each population without separating them! However, we would have to introduce quite a few new concepts to do so efficiently, so we are going to stick with the tried-and-true process of running the models individually.\n\nWe can use the `filter` function to select each population, one at a time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npop_NE <- pops %>% \n  filter(population == \"NE\")\n\npop_SE <- pops %>% \n  filter(population == \"SE\")\n\npop_SW <- pops %>% \n  filter(population == \"SW\")\n```\n:::\n\n\n### Finding the Carrying Capacity\n\nNow that we have data frames for each of the populations, we can fit the logistic model to each population and determine the estimate of the carrying capacity for each.\n\nAs we run the code to fit the model to each population, we might receive some warnings: \"Warning :NaNs produced\". Don't worry, that's ok! Keep going!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# NE population\nmodel_NE <- drm(abund ~ year, data = pop_NE, fct = LL.4())\nmodel_NE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nA 'drc' model.\n\nCall:\ndrm(formula = abund ~ year, data = pop_NE, fct = LL.4())\n\nCoefficients:\nb:(Intercept)  c:(Intercept)  d:(Intercept)  e:(Intercept)  \n       -3.883         86.783       1037.664          4.725  \n```\n\n\n:::\n\n```{.r .cell-code}\n# if you want to be fancy and save the carrying capacity as an object\n# this code combines several steps from the last lesson into one step\nK_NE <- unname(coef(model_NE)[3])\nK_NE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1037.664\n```\n\n\n:::\n:::\n\n\nNow we can do the same for the SE and SW populations, too.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# SE population\nmodel_SE <- drm(abund ~ year, data = pop_SE, fct = LL.4())\nmodel_SE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nA 'drc' model.\n\nCall:\ndrm(formula = abund ~ year, data = pop_SE, fct = LL.4())\n\nCoefficients:\nb:(Intercept)  c:(Intercept)  d:(Intercept)  e:(Intercept)  \n       -3.461         51.099        979.889          4.432  \n```\n\n\n:::\n\n```{.r .cell-code}\nK_SE <- unname(coef(model_SE)[3])\nK_SE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 979.8889\n```\n\n\n:::\n\n```{.r .cell-code}\n# SW population\nmodel_SW <- drm(abund ~ year, data = pop_SW, fct = LL.4())\nmodel_SW\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nA 'drc' model.\n\nCall:\ndrm(formula = abund ~ year, data = pop_SW, fct = LL.4())\n\nCoefficients:\nb:(Intercept)  c:(Intercept)  d:(Intercept)  e:(Intercept)  \n       -3.561         77.048        809.384          4.695  \n```\n\n\n:::\n\n```{.r .cell-code}\nK_SW <- unname(coef(model_SW)[3])\nK_SW\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 809.3843\n```\n\n\n:::\n:::\n\n\nLet's record the carrying capacity estimates for each population here so we can refer back to them later, if needed.\n\n| Population | Carrying Capacity  |\n|:----------:|:------------------:|\n|     NE     | 1037.7 |\n|     SE     | 979.9 |\n|     SW     | 809.4 |\n\nAs we saw in the plot, the estimated carrying capacity for the SW population is below that of the NE population.\n\nWhat was much more challenging to see clearly in the plot, however, is that the estimated carrying capacity of the SE population is in between the other two carrying capacities, albeit closer to the NE population.\n\n### Plotting the Logistic Model Curves\n\nWe can add the logistic growth models that we fit to each population into our ggplot to more easily compare the curves.\n\nTo do so requires a few steps.\n\n1.  Use the `predict()` function to get the values for the \"logistic line of best fit.\" Remember, these will not match up perfectly with our *actual, observed* values; these are the y-axis or `abundance` values for the best fitting logistic model at each observed x-axis value, or year.\n\n2.  Use the `mutate()` function to create a new column in each data frame with these logistic *model* values.\n\n3.  Combine all three dataframes back together into one dataframe using the `bind_rows()` function.\n\n4.  Plot the actual data points using `geom_point()` and plot the logistic model data points using the `geom_line()` function.\n\n#### Add the Logistic Model Points to the Dataframes\n\nFirst, let's see what output the `predict()` function gives us for the NE population.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(model_NE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]   86.78322   89.06604  119.38057  225.89179  413.57407  614.17858\n [7]  768.12217  867.83669  928.66760  965.64167  988.57434 1003.20806\n[13] 1012.82831 1019.33476 1023.85133 1027.06115 1029.39090 1031.11414\n[19] 1032.41057 1033.40091 1034.16792 1034.76945 1035.24658 1035.62899\n[25] 1035.93841 1036.19096\n```\n\n\n:::\n:::\n\n\nIf we compare these numbers to the numbers in the `abund` column of `pop_NE`, we notice that they are not the same. The difference between these values from the model of best fit and the actual, observed values are called *residuals*, just as they are with lines of best fit (from linear regressions).\n\n![](assets/residuals.jpg){width=\"50%\" fig-align=\"center\"}\n\nLet's use the `mutate` function to add these model values to each dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npop_NE <- pop_NE %>% \n  mutate(logistic_model = predict(model_NE))\npop_NE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 26 × 4\n    year abund population logistic_model\n   <dbl> <dbl> <chr>               <dbl>\n 1     0    51 NE                   86.8\n 2     1    70 NE                   89.1\n 3     2   164 NE                  119. \n 4     3   248 NE                  226. \n 5     4   431 NE                  414. \n 6     5   567 NE                  614. \n 7     6   723 NE                  768. \n 8     7   931 NE                  868. \n 9     8   931 NE                  929. \n10     9   987 NE                  966. \n# ℹ 16 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\npop_SE <- pop_SE %>% \n  mutate(logistic_model = predict(model_SE))\n\npop_SW <- pop_SW %>% \n  mutate(logistic_model = predict(model_SW))\n```\n:::\n\n\n#### Combine Dataframes\n\nWe can now bring all three individual data frames back together into one data frame using a function called `bind_rows()`. You can think of `bind_rows` as gluing the data frames together, one after another.\n\nThe arguments in the `bind_rows()` function are all of the data frames we want glued together.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npops_models <- bind_rows(pop_NE, pop_SE, pop_SW)\npops_models\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 78 × 4\n    year abund population logistic_model\n   <dbl> <dbl> <chr>               <dbl>\n 1     0    51 NE                   86.8\n 2     1    70 NE                   89.1\n 3     2   164 NE                  119. \n 4     3   248 NE                  226. \n 5     4   431 NE                  414. \n 6     5   567 NE                  614. \n 7     6   723 NE                  768. \n 8     7   931 NE                  868. \n 9     8   931 NE                  929. \n10     9   987 NE                  966. \n# ℹ 68 more rows\n```\n\n\n:::\n:::\n\n\nThe resulting data frame again has 78 observations, as did the original `pops` data frame.\n\n#### Add Logistic Models to the Plot\n\nWe can now add the logistic models to our plot using the `geom_line()` function. Specifically, the values from the `logistic_model` column will be the y-axis values for the lines we are adding; the x-axis values are the same as the overall plot: `year`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pops_models, aes(x = year, y = abund, color = population)) +\n  geom_point() +\n  geom_line(aes(y = logistic_model)) +\n  labs(x = \"Year\", y = \"Abundance\", color = \"Fish Population\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](module5_3_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nIt is now much easier to visually distinguish the differences between the growth curves and the carrying capacities between the three populations!\n\n## Statistically\n\nWe still want to analyze our three populations using inferential statistics to determine if there are significant differences between the populations.\n\nFirst, we need to decide what type of statistical test makes sense with the data we have. This is *not* a straight-forward question with a straight-forward answer. How we determine which test to use ultimately depends on the question we are asking and, therefore, the hypothesis we are testing.\n\nFor the sake of the class (and in your assignment, too), let's assume the question we want to ask is whether the average population sizes significantly differ between the populations.\n\nWhat type of statistical test should we use to answer that question?\n\nWhat would the null and alternative hypotheses be for that statistical test?\n\n::: instructor-only\n**Instructor Note:** An ANOVA. We have one numeric dependent variable (abundance) and one categorical independent variable (population) with three groups.\n\n-   **Null hypothesis:** The mean abundance is the same across all three populations during the leveled-off period.\n-   **Alternative hypothesis:** At least one population has a significantly different mean abundance.\n:::\n\n### Filtering the Data\n\nTo most accurately compare the populations, we likely want to restrict the comparison to when the populations (or the models of best fit, at least) are fairly leveled off.\n\n(Again, this is more of an estimation than an exact science, though there are more precise and complicated tools that could be used.)\n\nA rough estimation would be that the models mostly level off around year 15; let's filter our data to include only abundance from year 15 and later.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npops_15_25 <- pops_models %>% \n  filter(year >= 15)\npops_15_25\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 33 × 4\n    year abund population logistic_model\n   <dbl> <dbl> <chr>               <dbl>\n 1    15  1026 NE                  1027.\n 2    16  1024 NE                  1029.\n 3    17  1067 NE                  1031.\n 4    18  1010 NE                  1032.\n 5    19  1003 NE                  1033.\n 6    20  1026 NE                  1034.\n 7    21  1031 NE                  1035.\n 8    22  1034 NE                  1035.\n 9    23  1016 NE                  1036.\n10    24  1004 NE                  1036.\n# ℹ 23 more rows\n```\n\n\n:::\n:::\n\n\n### Running the Statistical Analysis\n\nNow that we have filtered our data, we can conduct our statistical test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_aov <- aov(abund ~ population, data = pops_15_25)\nsummary(model_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \npopulation   2 291562  145781   9.335 0.000704 ***\nResiduals   30 468491   15616                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThis p-value tells us that the overall model is significant (we reject the null hypothesis), but it doesn't tell us which populations are significantly different from one another. To determine which populations differ from each other, we need to run *post hoc* pairwise-comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(model_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = abund ~ population, data = pops_15_25)\n\n$population\n            diff       lwr       upr     p adj\nSE-NE  -74.45455 -205.8177  56.90861 0.3550427\nSW-NE -225.90909 -357.2722 -94.54593 0.0005622\nSW-SE -151.45455 -282.8177 -20.09139 0.0211521\n```\n\n\n:::\n:::\n\n\nHow do we interpret these results? What are our conclusions?\n\n::: instructor-only\n**Instructor Note:** The ANOVA is significant (p = 0.000704), meaning at least one population differs from the others. The Tukey HSD breaks it down:\n\n-   NE vs SE: not significantly different (p = 0.355)\n-   NE vs SW: significantly different (p = 0.0006) NE has higher abundance\n-   SE vs SW: significantly different (p = 0.021) SE has higher abundance\n\nConclusion: SW is significantly lower in abundance than both NE and SE. NE and SE are statistically similar to each other, but NE has a slightly higher carrying capacity.\n:::\n\n## Data-Driven Decision Making\n\nOur ultimate goal in this module has been to determine which population of fish is best for fishing sustainably. We are prioritizing large, stable populations.\n\nGiven those requirements and what our numeric, visual, and statistical tests have told us, which of these populations would be the best for us to harvest? Why?\n\n::: instructor-only\n**Instructor Note:** NE is the best choice, it has the highest carrying capacity and is significantly more abundant than SW.\n\nSE is also a reasonable choice since it is not statistically different from NE and has a substantially higher carrying capacity than SW.\n\nSW should be avoided: it is significantly less abundant than the other two and has the lowest carrying capacity, so it is least able to withstand fishing pressure.\n:::\n\n## References\n\nGolding, J.; Andersen, D.; Bledsoe, E. (2024). [Data-Driven Decision-Making: Antarctic Fisheries](http://dx.doi.org/10.25334/YECE-7M02). [Teaching Ecology for All Undergraduate Audiences](https://qubeshub.org/groups/teespring2024), QUBES Educational Resources. [doi:10.25334/YECE-7M02](http://dx.doi.org/10.25334/YECE-7M02)",
    "supporting": [
      "module5_3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}