{
  "hash": "bd4386ef6ec3befe71ffe831c611b120",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"4.3: Roads and Regressions\"\nauthor: \"Mila Pruiett and Ellen Bledsoe\"\nformat:\n  html:\n    toc: true\n---\n\n\n\n# Roads and Regressions\n\n## Learning Outcomes\n\n-   Students will be able to create a scatter plot with a line of best fit using `geom_smooth()`.\n-   Students will be able to calculate and interpret a correlation coefficient and R-squared value.\n-   Students will be able to run a linear regression using `lm()` and interpret the output including slope, intercept, and p-value.\n-   Students will be able to use regression results to inform a data-driven decision.\n\n## The Scenario\n\nIn this module, we have tried to figure out which bays we should prioritize for fishing based on the following data sets:\n\n-   radio collar data\n-   fish catch data\n-   leopard seal abundance data\n\nBased on our results from Assignment 2, we made a decision about which two bays look like our best options. Now, we need to make these bays accessible over land to transport the fish we've caught to our home base.\n\n**Our Goal: build a road while minimizing our impact on the delicate antarctic ecosystem.**\n\nOur first order of business is to make sure that we avoid areas that are well-suited for [Antarctica hair grass](https://oceanwide-expeditions.com/blog/the-plants-of-antarctic) (*Deschampsia antarctica*), one of only two flowering species of plants on the continent.\n\n![](assets/hairgrass_indiv.jpeg){width=\"50%\"}\n\nWe want to know what environmental conditions are associated with hair grass. This way, we can avoid areas where these conditions are met and not destroy precious habitat for the hair grass.\n\nIt would take far too long to survey every bit of land between our base and our fishing spots, so we are going to build a **model** based on some samples of where hair grass is found to help us predict where else it might be.\n\n### What is a model?\n\nA model is a way for us to take complex systems and break them down into small, more understandable bits. We can use models to help us understand the relationship between different variables. We can then use those models to make predictions based on those relationships.\n\n## Data\n\n![](assets/hairgrass_landscape.jpeg){width=\"50%\"}\n\nKnowing that we would soon be building roads, we asked our botanists to collect data for us on key components of the hairgrass' environment. Since it would take too long to sample everywhere hairgrass grows, they collected data from a sample of the hairgrass population.\n\nOur botanists collected data for the following variables:\n\n-   *hairgrass density*: number of individual clumps (tussocks) of hairgrass (per 25 meters squared)\n-   *soil pH*: most plants prefer mildly acidic to neutral environments\n-   *nitrogen (N) content*: as parts per million (ppm); important for plant growth and tissue building\n-   *phosphorous (P) content*: as parts per million (ppm); important for plant growth and tissue building\n-   *percent rock*: how rocky the location is; rocks in soil impact water drainage and temperature\n-   *max windspeed (knots per hour)*: extreme wind can pose a challenge to plants of all types\n-   *average summer temperature (C)*: temperature in the growing season\n-   *penguin density*: the number of penguins per the sample quadrant: penguin poop increases nitrogen and phosphorus content in the system but penguins may trample the plants\n\nThis data is based on this article: [Parnikoza, et al. 2007](https://doi.org/10.1016/j.polar.2007.10.002)\n\n## Summarize and Visualize\n\nAs we see above, there are many environmental conditions that may be associated with hair grass density.\n\nFor this lesson, we are going to focus on two: *nitrogen (N) content* and *soil pH*.\n\n### Set-Up\n\nAs usual, we start with loading tidyverse and our data. Read in \"data/hairgrass_data.csv\" and save it as an object called `hairgrass_data`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n::: instructor-only\n**Answer:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nhairgrass_data <- read_csv(\"data/hairgrass_data.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 240 Columns: 8\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (8): hairgrass_density, soil_nitrogen, soil_phosphorus, penguin_density,...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n:::\n\nLet's take a look at the data in the data set. What does each row represent?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(hairgrass_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  hairgrass_density soil_nitrogen soil_phosphorus penguin_density\n              <dbl>         <dbl>           <dbl>           <dbl>\n1               137          17.0            6.44              15\n2               103          20.1            5.96              21\n3               107          12.4            7.69              10\n4               121          13.2            6.76              22\n5               150          25.9            7.16              14\n6               120          15.3            3.04              14\n# ℹ 4 more variables: avg_summer_tempC <dbl>, avg_windspeed <dbl>,\n#   soil_ph <dbl>, percent_rock <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(hairgrass_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  hairgrass_density soil_nitrogen soil_phosphorus penguin_density\n              <dbl>         <dbl>           <dbl>           <dbl>\n1               117          10.6            5.29              23\n2               129          19.2            4.03              21\n3               115          19.3            6.25              10\n4               152          26.9            7.57              14\n5               135          14.9            5.54              19\n6               126          24.0            5.24              18\n# ℹ 4 more variables: avg_summer_tempC <dbl>, avg_windspeed <dbl>,\n#   soil_ph <dbl>, percent_rock <dbl>\n```\n\n\n:::\n:::\n\n\n### Nitrogen Content\n\nLet's start by investigating any relationship between hair grass density and nitrogen content.\n\nFirst, we should spend a little time thinking about our variables. Spend a few minutes in small groups discussing the answer to the questions below.\n\n-   Which columns are we interested in right now?\n-   Which one is the independent variable and which is the dependent variable?\n-   Are the variables categorical or continuous?\n-   Which type of data visualization should we use?\n\n::: instructor-only\n**Answers:** - soil_nitrogen and hairgrass_density - independent = soil_nitrogen, dependent = hairgrass_density - both continuous - scatter plot\n:::\n\nNext, calculate the mean (`mean()`) and standard deviation (`sd()`) for the nitrogen content.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhairgrass_data %>% \n  summarise(mean_N = mean(soil_nitrogen),\n            sd_N = sd(soil_nitrogen))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  mean_N  sd_N\n   <dbl> <dbl>\n1   19.9  4.73\n```\n\n\n:::\n:::\n\n\nNow that we have summarized the data, let's take a look at the data visually.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hairgrass_data, aes(soil_nitrogen, hairgrass_density)) +\n  geom_point() +\n  labs(x = \"N Content\",\n       y = \"Hairgrass Density (per 25 m^2)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](module4_3_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nDo you see a pattern? What type of relationship do you see?\n\nHow do we analyze this type of relationship statistically?\n\n## Statistical Analysis\n\nWe are going to use two (related) statistical methods to understand the relationship between two continuous (numeric) variables:\n\n-   correlation coefficient ($r$) and R-squared ($R^2$)\n-   linear regression\n\n### Line of Best Fit\n\nTo understand correlation, R-squared, and linear regression, we first need to talk about something we call the *line of best fit*.\n\nThe line of best fit aims to minimize the distance between each observation (points) and the line. The distances between each observation and any line are called *residuals* (the dotted gray lines). The line of best fit is the line that has the smallest *residuals*.\n\n![](assets/lines.png){width=\"50%\"} ![](assets/residuals.jpg){width=\"50%\"}\n\nWe can add a line of best fit to a ggplot by using the `geom_smooth()` function. We need to specify that the method we want should produce a straight line (\"linear model\").\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hairgrass_data, aes(soil_nitrogen, hairgrass_density)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(x = \"N Content\",\n       y = \"Hairgrass Density (per 25 m^2)\") +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](module4_3_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# method = \"lm\" is required!\n# se = FALSE is optional\n```\n:::\n\n\n### Correlation Coefficient\n\nThe correlation coefficient, `r`, is a measurement of the strength of the relationship between two continuous variables.\n\nThe correlation coefficient is a number between -1 and 1 that looks at the relationship between two numeric variables. If the value is negative, there is a negative relationship between the two variable; if the value is positive, there is a positive relationship.\n\nIf all the points fall exactly on the line of best fit, r = 1 or -1. If there is no relationship between the variables, `r` is 0 (or something very close to it).\n\n![](assets/coefficient_correlation.jpg){width=\"50%\"}\n\nThe greater the magnitude (size) of the correlation coefficient, the stronger the relationship between the two variables.\n\n![](assets/correlation.jpg){width=\"50%\"}\n\nIt is also important to recognize that the correlation coefficient has nothing to do with the slope of the line (we use linear regression to assess that!)\n\n![](assets/steepness.jpeg){width=\"50%\"}\n\nBased on the hairgrass plot we did above, do you expect the correlation coefficient to be positive or negative? For this class, we'll say that any `r` value within 0.1 of 0 means there is no relationship.\n\nTo calculate the correlation coefficient, we need to go back to base R and indicate which columns we are referencing with the `$` operator. We use the `cor()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr_nitrogen <- cor(x = hairgrass_data$soil_nitrogen, y = hairgrass_data$hairgrass_density)\nr_nitrogen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5952863\n```\n\n\n:::\n:::\n\n\n### R-squared ($R^2$)\n\nThe R-squared ($R^2$) value is a representation of how much variation is explained by the line of best fit.\n\nWhen we have a dependent variable and an independent variable, the R-squared value tells us how much of the variation in the *dependent* variable is explained by the *independent* variable.\n\nSometimes we don't have obvious dependent and independent variables, but we can still use similar language ($R^2$ tells us how much of the variation in the data is explained).\n\nTo calculate R-squared, we square the correlation coefficient value we calculated above. It is always positive because we are squaring the `r` value; that means that R-squared values range from 0 to 1. The closer to 1, the more variation is explained.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr_nitrogen^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3543658\n```\n\n\n:::\n:::\n\n\nHow would we interpret this `r^2` value?\n\n::: instructor-only\n**Instructor Note:** r = 0.595. a moderate positive relationship. r\\^2 = 0.354, meaning nitrogen content explains about 35% of the variation in hairgrass density. This is a meaningful relationship for ecological data.\n:::\n\nOne way to think of the `r^2` value that might be helpful is to convert it from a proportion to a percentage—what *percentage* of the variation in the dependent variable is explained by the independent variable?\n\nTo convert the proportion to a percentage, we can multiply the value by 100.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr_nitrogen^2 * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 35.43658\n```\n\n\n:::\n:::\n\n\n### Linear Regression Analysis\n\nA regression analysis approximates the relationship between a dependent variable and one or more independent variables. It evaluates the strength of that relationship, ultimately giving us a p-value.\n\nSince we are using linear regressions in this course, the regression model will take the form of a straight line. The generic equation for a straight line is `y = mx + b`.\n\n-   `y` = dependent variable (y-axis)\n-   `x` = independent variable (x-axis)\n-   `m` = slope of the line\n-   `b` = y-intercept\n\nWhen we have a line with the specific slope and y-intercept, this equation lets us calculate the expected y-axis value for any given point on the x-axis.\n\nUsing our variables, what would our linear regression model look like (we don't know `m` or `b` yet...)?\n\n### Hypothesis Testing\n\nWhat is the null hypothesis? What is the alternative hypothesis?\n\n**Null Hypothesis** ($H_{0}$): There is no relationship between hair grass density and nitrogen content.\n\n**Alternative Hypothesis** ($H_{A}$): There is a relationship between hair grass density and nitrogen content.\n\nWhat do you think this means for the slopes?\n\n::: instructor-only\n**Instructor Note:** The null hypothesis of no relationship corresponds to a slope of 0. If there's no relationship, the line of best fit would be flat. The alternative hypothesis implies a non-zero slope (either positive or negative).\n:::\n\n### Regression Analysis\n\nThankfully, R can calculate the slope (`m`) and y-intercept (`b`) of the line of best fit for us.\n\nLet's find the equation for our line of best fit, our test statistic, and our p-value. To do this, we use a function called `lm()`: this stands for \"linear model.\"\n\nLike with ANOVA, we will then want to use the `summary()` function to get out the values we need.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnitrogen_model <- lm(hairgrass_density ~ soil_nitrogen, data = hairgrass_data)\nsummary(nitrogen_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = hairgrass_density ~ soil_nitrogen, data = hairgrass_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-29.1517  -8.5534   0.3784   9.3032  23.8779 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    84.2416     3.2267   26.11   <2e-16 ***\nsoil_nitrogen   1.8027     0.1577   11.43   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.54 on 238 degrees of freedom\nMultiple R-squared:  0.3544,\tAdjusted R-squared:  0.3517 \nF-statistic: 130.6 on 1 and 238 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAs with our other statistical tests---t-tests and ANOVAs---the results give us some important values:\n\n-   `b` (y-intercept): part of our line of best fit equation\n    -   The \"intercept estimate\", in this case 84.24, is our y-intercept in our line of best fit\n-   `m` (slope): also part of our line of best fit equation\n    -   this is the estimate for our independent variable (soil_nitrogen in this case)\n    -   in this model, m = 1.8\n-   *F-statistic*: this is our test statistic\n-   *p-value*: calculated from our regression model, used to determine significance (0.05 cut-off, as usual)\n    -   There are multiple p-values here. Focus either on the p-value for the independent variable (soil_nitrogen) or the overall p-value displayed in the last line of the results summary (p \\< 2.2e-16)\n-   *R-squared*: this is our R-squared value that we calculated earlier\n    -   You can report either the \"multiple\" or the \"adjusted\"\n    -   The \"multiple\" will typically match the one we calculate with code\n\nThis means our equation for the line of best fit is: y = 1.8x + 84.24 and there is a statistically significant relationship between nitrogen content and hairgrass density.\n\n## Soil pH\n\nLet's do the same series of steps to determine how soil pH impacts hair grass densities.\n\nWork on this in your small groups.\n\n::: instructor-only\n**Instructor Note:** Work in small groups for about 10 minutes, then review as a class.\n:::\n\nStart with summarizing the data: mean and standard deviation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\nVisualize the data. Remember to add in the line of best fit using `ggplot2`. Also add labels and a theme.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\nCalculate the correlation coefficient (`r`). What does this tell us?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\nHow much variation does soil pH explain in the hair grass density data?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\nWrite out the model equation for our question about soil pH (without values).\n\nRun the regression model and write out the equation for the line of best fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\nInterpret the results of the regression. What do we conclude about the relationship between soil pH and hair grass density, and why?\n\n::: instructor-only\n**Answers:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhairgrass_data %>% \n  summarize(mean_pH = mean(soil_ph),\n            sd_pH = sd(soil_ph))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  mean_pH sd_pH\n    <dbl> <dbl>\n1    6.48 0.405\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hairgrass_data, aes(soil_ph, hairgrass_density)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(x = \"Soil pH\",\n       y = \"Hairgrass Density (per 25 m^2)\") + \n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](module4_3_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr_ph <- cor(x = hairgrass_data$soil_ph, y = hairgrass_data$hairgrass_density)\nr_ph\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.1313161\n```\n\n\n:::\n:::\n\n\nr = -0.131. a weak negative relationship, barely outside the \"no relationship\" threshold of 0.1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr_ph^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01724392\n```\n\n\n:::\n:::\n\n\n`r^2` = 0.017. soil pH explains only about 1.7% of the variation in hairgrass density.\n\nModel form: hairgrass_density = m(soil_ph) + b\n\n\n::: {.cell}\n\n```{.r .cell-code}\nph_model <- lm(hairgrass_density ~ soil_ph, data = hairgrass_data)\nsummary(ph_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = hairgrass_density ~ soil_ph, data = hairgrass_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-38.165 -10.271   0.634  11.391  34.034 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  150.240     14.765  10.175   <2e-16 ***\nsoil_ph       -4.648      2.274  -2.044   0.0421 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14.23 on 238 degrees of freedom\nMultiple R-squared:  0.01724,\tAdjusted R-squared:  0.01311 \nF-statistic: 4.176 on 1 and 238 DF,  p-value: 0.0421\n```\n\n\n:::\n:::\n\n\nEquation for line of best fit: y = -4.648x + 150.24\n\np = 0.0421, which is less than 0.05, so we reject the null hypothesis. There is a statistically significant relationship between soil pH and hairgrass density.\n\nHowever, look at `r^2` = 0.017. That means soil pH explains only 1.7% of the variation in hairgrass density. The relationship is real but extremely weak.\n\n**A p-value tells us whether a relationship exists, r\\^2 tells us how strong it is. Here, the relationship technically exists but is far too weak to be a meaningful predictor. Nitrogen (r\\^2 = 0.354, explaining 35% of variation) is a way better predictor of where hairgrass thrives.**\n:::\n\n## Data-driven Decision Making\n\nThe reason we are using regression analysis is to inform where we should (or should not) build our road so we don't harm the sensitive hair grass or take away their prime habitat.\n\nWhat do results above for nitrogen content and soil pH mean for the road we are building?\n\n::: instructor-only\n**Instructor Note:** Nitrogen content is by far the stronger predictor. r\\^2 = 0.354, meaning it explains 35% of the variation in hairgrass density (p \\< 2.2e-16). Higher nitrogen strongly predicts higher hairgrass density. **Road planning should prioritize avoiding high-nitrogen areas.**\n\nSoil pH is statistically significant (p = 0.0421) but practically very weak. r\\^2 = 0.017 means it explains only 1.7% of the variation. While the negative slope suggests more acidic soils have slightly higher density, this relationship is too weak to be a reliable guide on its own.\n\n**p \\< 0.05 tells us a relationship exists, but r\\^2 tells us whether it is actually strong enough to be useful.** Soil pH passes the significance threshold but fails the usefulness test.\n:::",
    "supporting": [
      "module4_3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}